apiVersion: v1
kind: Service
metadata:
  labels:
    app: lbtester
  name: lbtester-service
  namespace: sample-namespace
spec:
  selector:
    app: lbtester
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 8888
  type: NodePort