apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbtester-deployment
  namespace: sample-namespace
  labels:
    app: lbtester
spec:
  replicas: 50
  selector:
    matchLabels:
      app: lbtester
  template:
    metadata:
      labels:
        app: lbtester
    spec:
      containers:
      - name: lbtester
        image: tomj0101/lbtester:lasted
        # Changing from imagePullPolicy: Never to Always for local k8s LABs         
        imagePullPolicy: Always
        ports:
        - containerPort: 8888